---     
- name: Playbook for packages.yml
  hosts: web
  gather_facts: false
  remote_user: centos
  #become: true
  #become_user: root
  #become_method: sudo
  vars: 
    pkgs:
      - httpd
      - php
      - mariadb
  tasks:
    - name: Ping check
      ping:
      
    - name: install the packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ pkgs }}"
