---     
- name: Playbook for packages.yml
  hosts: all
  gather_facts: false
  become: false
  #become_user: root
  #become_method: sudo
  #become_ask_pass: false
  remote_user: nived
  tasks:
    - name: Ping check
      ping:
      
    - name: install the packages
      dnf:
        name: httpd
        state: latest
      register: this
    - debug:
        var: this
      
    
