---     
- name: Playbook for packages.yml
  hosts: all
  gather_facts: false
  #become: yes
  ignore_errors: yes
  #become_user: root
  #become_method: sudo
  #become_ask_pass: false
  remote_user: nived
  tasks:
    - name: Ping check
      ping:
    - name: check id
      register: uptimeoutput
      command: "id"
    - debug:
        var: uptimeoutput  
    - name: check id
      register: thisnew
      command: "hostname"
    - debug:
        var: thisnew 
    - name: install the packages
      yum:
        name: httpd
        state: latest
      register: this
    - debug:
        var: this
      
    
