---     
- name: Playbook for packages.yml
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  become_method: sudo
  remote_user: devops
  vars: 
    pkgs:
      - httpd
  tasks:
    - name: Ping check
      ping:
      
    - name: install the packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ pkgs }}"
