---     
- name: Playbook for packages.yml
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  become_method: sudo
  #become_ask_pass: false
  remote_user: nived
  tasks:
    - name: Ping check
      ping:
      
    - name: install the packages
      package:
        name: "httpd"
        state: present
      register: this
    - debug:
        var: this
      
    
