---     
- name: Playbook for packages.yml
  hosts: web
  vars: 
    pkgs:
      - httpd
      - php
      - mariadb
  tasks:
    - name: install the packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ pkgs }}"
